---
language: python
matrix:
  include:

    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      dist: xenial          # required for Python >= 3.7

    - name: "Python 3.7.2 on macOS"
      os: osx
      osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
#     - name: "Python 3.7.3 on Windows"
#       os: windows           # Windows 10.0.17134 N/A Build 17134
#       language: shell       # 'language: python' is an error on Travis CI Windows
#       before_install: choco install python3
#       env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

before_install: pip3 install --upgrade pip
before_install: python -m pip install --upgrade pip
# all three OSes agree about 'pip3'
# 'python' points to Python 2.7 on macOS but points to Python 3.7 on Linux and Windows
# 'python3' is a 'command not found' error on Windows but 'py' works on Windows only 

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip
install:
# Install ansible
  - pip install ansible
# Install ansible reveiw
  - pip install ansible-review

# Install ansible-lint
  - pip install ansible-lint

# Install yamllint
  - pip install yamllint

  # # Create ansible.cfg with correct roles_path
  # - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Check ansible version
  - ansible --version

  # Check syntax
  - ansible-review --version

  # Basic role syntax check
  - ansible-playbook -i tests/inventory tests/test.yml  --syntax-check

  - git ls-files | grep -Ei '^[^[:punct:]].+.(yaml|yml)$' | xargs ansible-review -q

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
