---
- name: Set Enforce password history to 24 or more passwords | cis enforce-password-history 1.1.1
  win_command: net accounts /uniquepw:24
  register: passHistory
  args:
    creates: C:\passHistory.lock

- name: Create passHistory.lock if password history is enforced
  win_copy:
    dest: C:\passHistory.lock
    content: ""
    force: no
  when: passHistory

- name: Set Maximum password age to 60 or more days | cis maximum-password-age 1.1.2
  win_command: net accounts /maxpwage:60
  register: maxPassAge
  args:
    creates: C:\maxPassAge.lock

- name: Create maxPassAge.lock if password history is enforced
  win_copy:
    dest: C:\maxPassAge.lock
    content: ""
    force: no
  when: maxPassAge

- name: Set Minimum password age to 1 or more days | cis minimum-password-age 1.1.3
  win_command: net accounts /minpwage:1
  register: minPassAge
  args:
    creates: C:\minPassAge.lock

- name: Create minPassAge.lock if password history is enforced
  win_copy:
    dest: C:\minPassAge.lock
    content: ""
    force: no
  when: minPassAge

- name: Set Minimum password length to 14 or more characters | cis minimum-password-length 1.1.4
  win_command: net accounts /minpwlen:14
  register: minPassLength
  args:
    creates: C:\minPassLength.lock

- name: Create minPassLength.lock if password history is enforced
  win_copy:
    dest: C:\minPassLength.lock
    content: ""
    force: no
  when: minPassLength
